
import React,{useEffect,useMemo,useState}from"react";
import{createRoot}from"react-dom/client";
import{createClient}from"@supabase/supabase-js";
import{Home,ScrollText,BookOpen,Trophy,Shield,Users,Store,Bot,BarChart3,Settings,Flame,Bell,Play,Star,Lock,Leaf,Calculator,Atom,FlaskConical,LogOut,Sun,Moon,Send,Copy,CheckCircle2,Target,X,Search,UserRound,Palette}from"lucide-react";
import"./styles.css";

const supabase=createClient(import.meta.env.VITE_SUPABASE_URL||"",import.meta.env.VITE_SUPABASE_ANON_KEY||"");
const LEVELS=["National 5","Higher","Advanced Higher"];
const SCHOOLS=["Dumfries High School","Wallace Hall Academy","Sanquhar Academy","St Joseph's College","Dalbeattie High School","Annan Academy","Lockerbie Academy","Moffat Academy","Castle Douglas High School","Kirkcudbright Academy","Other Scottish School"];
const AVATARS=["🦊","🐼","🐧","🐸","🐯","🐻","🐨","🦁","🐵","🐰","🦉","🐺"];
const HOUSES=["NITH","SCAUR","CAIRN"];
const TOPICS={
Biology:{icon:<Leaf/>,color:"green","National 5":[["Cell Biology","Cell structure, transport, DNA, enzymes, respiration and photosynthesis."],["Multicellular Organisms","Specialised cells, tissues, organs, control, reproduction and inheritance."],["Life On Earth","Ecosystems, sampling, biodiversity, food chains, energy and human impact."]],Higher:[["DNA And The Genome","DNA structure, replication, gene expression, mutations and genomics."],["Metabolism And Survival","Metabolic pathways, enzymes, respiration, photosynthesis and survival adaptations."],["Sustainability And Interdependence","Food supply, plant growth, animal welfare, populations and biodiversity."]],"Advanced Higher":[["Cells And Proteins","Laboratory techniques, proteins, membranes, communication and cell behaviour."],["Organisms And Evolution","Field techniques, evolution, variation, selection and animal behaviour."],["Investigative Biology","Planning, carrying out, analysing and evaluating a biology investigation."]]},
Maths:{icon:<Calculator/>,color:"blue","National 5":[["Expressions And Formulae","Algebra, indices, surds, factorising, formulae and equations."],["Relationships","Graphs, straight lines, quadratics, trigonometry and geometry."],["Applications","Statistics, probability, vectors, percentages and real-life problem solving."]],Higher:[["Expressions And Functions","Polynomials, logs, functions, graphs and algebraic manipulation."],["Relationships And Calculus","Differentiation, integration, trigonometry and equations."],["Applications","Vectors, recurrence relations, optimisation and applying mathematical methods."]],"Advanced Higher":[["Methods In Algebra And Calculus","Advanced algebra, integration, differentiation and differential equations."],["Applications Of Algebra And Calculus","Using advanced methods to model and solve complex problems."],["Geometry, Proof And Systems","Vectors, matrices, complex numbers, proof and systems of equations."]]},
Physics:{icon:<Atom/>,color:"purple","National 5":[["Dynamics And Space","Velocity, acceleration, forces, energy, projectiles and space."],["Electricity And Energy","Circuits, power, specific heat capacity, gas laws and conservation."],["Waves And Radiation","Wave properties, light, sound, nuclear radiation and applications."]],Higher:[["Our Dynamic Universe","Motion, forces, relativity, gravitation, cosmology and the expanding universe."],["Particles And Waves","Standard Model, nuclear reactions, waves, interference and spectra."],["Electricity","Fields, circuits, capacitors, semiconductors and electrical principles."],["Researching Physics","Practical investigation skills, uncertainty, graphs and scientific reporting."]],"Advanced Higher":[["Rotational Motion And Astrophysics","Angular motion, gravitation, orbital motion and astrophysics."],["Quanta And Waves","Quantum theory, wave-particle duality, interference and wave behaviour."],["Electromagnetism","Fields, induction, circuits and electromagnetic applications."],["Investigating Physics","Designing, carrying out and reporting an advanced physics investigation."]]},
Chemistry:{icon:<FlaskConical/>,color:"orange","National 5":[["Chemical Changes And Structure","Rates, atomic structure, bonding, formulae and reaction quantities."],["Nature's Chemistry","Fuels, hydrocarbons, alcohols, acids, esters and natural products."],["Chemistry In Society","Metals, plastics, fertilisers, batteries, analysis and chemical industry."]],Higher:[["Chemical Changes And Structure","Periodicity, bonding, energetics, rates, equilibria and calculations."],["Nature's Chemistry","Systematic organic chemistry, fuels, proteins, fats and oxidation."],["Chemistry In Society","Industrial chemistry, redox, chemical analysis and environmental chemistry."],["Researching Chemistry","Practical skills, experimental design, uncertainty and scientific communication."]],"Advanced Higher":[["Inorganic Chemistry","Electronic structure, transition metals, bonding and inorganic reactions."],["Physical Chemistry","Thermodynamics, kinetics, equilibria and electrochemistry."],["Organic Chemistry","Mechanisms, synthesis, stereochemistry and organic analysis."],["Instrumental Analysis","Spectroscopy, chromatography and interpreting chemical evidence."],["Researching Chemistry","Advanced practical research, planning, analysis and evaluation."]]}
};
const SHOP=[{id:"double_xp",name:"Double XP Potion",icon:"🧪",costType:"gems",cost:3,desc:"Next study session earns double XP."},{id:"coin_charm",name:"Coin Charm",icon:"🪙",costType:"coins",cost:40,desc:"Next study session earns double coins."},{id:"gem_finder",name:"Gem Finder",icon:"💎",costType:"coins",cost:75,desc:"Next study session earns two bonus gems."},{id:"streak_shield",name:"Streak Shield",icon:"🛡️",costType:"gems",cost:5,desc:"Decorative shield for your profile."}];

function today(){return new Date().toISOString().slice(0,10)}
function weekStart(){const d=new Date(),day=(d.getDay()+6)%7;d.setDate(d.getDate()-day);return d.toISOString().slice(0,10)}
function minutesLabel(m){m=Number(m||0);const h=Math.floor(m/60),mm=m%60;return h?`${h}h ${mm}m`:`${mm}m`}
function levelFromXP(xp){return Math.max(1,Math.floor(Math.sqrt(Number(xp||0)/80))+1)}
function calcStreak(sessions){const days=[...new Set((sessions||[]).map(s=>s.session_date))].sort().reverse();let st=0,d=new Date(today()+"T00:00:00");for(let i=0;i<365;i++){const k=d.toISOString().slice(0,10);if(days.includes(k)){st++;d.setDate(d.getDate()-1);continue}if(i===0){d.setDate(d.getDate()-1);continue}break}return st}
function safeName(email){return(email||"student").split("@")[0].replace(/[^a-zA-Z0-9_]/g,"").slice(0,18)||"student"}
function copyText(t){navigator.clipboard?.writeText(String(t||""))}
function titleCase(s){return String(s||"").replace(/\b\w/g,c=>c.toUpperCase())}

function App(){
 const[session,setSession]=useState(null),[loading,setLoading]=useState(true),[theme,setTheme]=useState(localStorage.getItem("rr_theme")||"light");
 useEffect(()=>{document.body.dataset.theme=theme;localStorage.setItem("rr_theme",theme)},[theme]);
 useEffect(()=>{supabase.auth.getSession().then(({data})=>{setSession(data.session);setLoading(false)});const{data:{subscription}}=supabase.auth.onAuthStateChange((_e,s)=>setSession(s));return()=>subscription.unsubscribe()},[]);
 if(loading)return <div className="loading">Loading RevisionRoyale...</div>;
 if(!session)return <Auth theme={theme} setTheme={setTheme}/>;
 return <Game user={session.user} theme={theme} setTheme={setTheme}/>;
}
function Auth({theme,setTheme}){
 const[mode,setMode]=useState("login"),[email,setEmail]=useState(""),[password,setPassword]=useState(""),[username,setUsername]=useState(""),[school,setSchool]=useState(SCHOOLS[0]),[house,setHouse]=useState("NITH"),[avatar,setAvatar]=useState("🦊"),[msg,setMsg]=useState("");
 async function submit(){setMsg("");const result=mode==="login"?await supabase.auth.signInWithPassword({email,password}):await supabase.auth.signUp({email,password,options:{data:{username:username||safeName(email),school,house,avatar}}});if(result.error)setMsg(result.error.message);else if(mode==="signup")setMsg("Account Created. Check Your Email If Needed, Then Log In.")}
 return <main className="auth-v2"><section className="welcome-side"><div className="floating">{avatar}</div><h1>Ready For A Study Quest?</h1><p>Earn XP, Unlock Topics, Join Your House And Compete With Your School.</p><div className="bubble-row"><span>🔥 Streaks</span><span>💎 Gems</span><span>🏆 Houses</span></div></section><section className="auth-card-v2"><div className="logo wide"><Fox tiny/><h1>Revision<span>Royale</span></h1></div><h2>{mode==="login"?"Welcome Back":"Create Your Character"}</h2><div className="auth-tabs"><button className={mode==="login"?"on":""} onClick={()=>setMode("login")}>Login</button><button className={mode==="signup"?"on":""} onClick={()=>setMode("signup")}>Sign Up</button></div>{msg&&<div className="notice">{msg}</div>}<input placeholder="Email" value={email} onChange={e=>setEmail(e.target.value)}/><input placeholder="Password" type="password" value={password} onChange={e=>setPassword(e.target.value)}/>{mode==="signup"&&<><input placeholder="Username, e.g. Baker07" value={username} onChange={e=>setUsername(e.target.value)}/><select value={school} onChange={e=>setSchool(e.target.value)}>{SCHOOLS.map(s=><option key={s}>{s}</option>)}</select><select value={house} onChange={e=>setHouse(e.target.value)}>{HOUSES.map(h=><option key={h}>{h}</option>)}</select><AvatarPicker avatar={avatar} setAvatar={setAvatar}/></>}<button className="big" onClick={submit}>{mode==="login"?"Enter The Kingdom":"Start My Quest"}</button><button className="plain" onClick={()=>setTheme(theme==="light"?"dark":"light")}>{theme==="light"?<Moon/>:<Sun/>} Switch Theme</button></section></main>
}
function Game({user,theme,setTheme}){
 const[page,setPage]=useState("home"),[profile,setProfile]=useState(null),[sessions,setSessions]=useState([]),[friends,setFriends]=useState([]),[subject,setSubject]=useState(localStorage.getItem("rr_subject")||"Biology"),[courseLevel,setCourseLevel]=useState(localStorage.getItem("rr_level")||"Higher"),[toast,setToast]=useState(""),[notifs,setNotifs]=useState(false),[loading,setLoading]=useState(true);
 useEffect(()=>localStorage.setItem("rr_subject",subject),[subject]);useEffect(()=>localStorage.setItem("rr_level",courseLevel),[courseLevel]);
 function notify(t){setToast(t);setTimeout(()=>setToast(""),2600)}
 async function ensureProfile(){let{data:p}=await supabase.from("profiles").select("*").eq("id",user.id).maybeSingle();if(!p){const md=user.user_metadata||{},username=md.username||safeName(user.email);const{data:newP}=await supabase.from("profiles").insert({id:user.id,email:user.email,username,display_name:username,school:md.school||SCHOOLS[0],house:md.house||"NITH",avatar:md.avatar||"🦊",coins:0,gems:0,active_boost:null}).select("*").single();p=newP}return p}
 async function load(){setLoading(true);const p=await ensureProfile();const[s,f]=await Promise.all([supabase.from("study_sessions").select("*").eq("user_id",user.id).order("created_at",{ascending:false}),supabase.from("friends_view").select("*").or(`requester.eq.${user.id},receiver.eq.${user.id}`)]);setProfile(p);setSessions(s.data||[]);setFriends(f.data||[]);setLoading(false)}
 useEffect(()=>{load()},[]);
 const stats=useMemo(()=>{const xp=sessions.reduce((a,s)=>a+Number(s.xp||0),0),todayS=sessions.filter(s=>s.session_date===today()),week=sessions.filter(s=>s.session_date>=weekStart());return{xp,levelNum:levelFromXP(xp),coins:Number(profile?.coins||0),gems:Number(profile?.gems||0),activeBoost:profile?.active_boost||"",streak:calcStreak(sessions),total:sessions.reduce((a,s)=>a+Number(s.minutes||0),0),todayMinutes:todayS.reduce((a,s)=>a+Number(s.minutes||0),0),todayCount:todayS.length,week:week.reduce((a,s)=>a+Number(s.minutes||0),0)}},[sessions,profile]);
 if(loading)return <div className="loading">Loading Your Quest Map...</div>;
 const notifications=[`You Have A ${stats.streak} Day Streak`,stats.activeBoost?`${boostName(stats.activeBoost)} Is Active`:"No Boost Active",`You Have ${stats.coins} Coins And ${stats.gems} Gems`];
 return <div className="shell">
  <aside className="sidebar"><div className="logo sidebar-logo"><Fox tiny/><h1>Revision<span>Royale</span></h1></div><Nav page={page} setPage={setPage} id="home" icon={<Home/>} label="Home"/><Nav page={page} setPage={setPage} id="quests" icon={<ScrollText/>} label="Quests"/><Nav page={page} setPage={setPage} id="study" icon={<BookOpen/>} label="Study"/><Nav page={page} setPage={setPage} id="leaderboard" icon={<Trophy/>} label="Leaderboard"/><Nav page={page} setPage={setPage} id="house" icon={<Shield/>} label="House"/><Nav page={page} setPage={setPage} id="friends" icon={<Users/>} label="Friends"/><Nav page={page} setPage={setPage} id="shop" icon={<Store/>} label="Shop"/><Nav page={page} setPage={setPage} id="character" icon={<UserRound/>} label="Character"/><Nav page={page} setPage={setPage} id="ai" icon={<Bot/>} label="AI Coach"/><Nav page={page} setPage={setPage} id="stats" icon={<BarChart3/>} label="Stats"/><Nav page={page} setPage={setPage} id="settings" icon={<Settings/>} label="Settings"/><ProfileCard profile={profile} stats={stats}/><button className="logout" onClick={()=>supabase.auth.signOut()}><LogOut/> Sign Out</button></aside>
  <main className="main"><PageHeader title={pageTitle(page)} profile={profile} stats={stats} theme={theme} setTheme={setTheme} setNotifs={setNotifs}/>{toast&&<div className="toast">{toast}</div>}{notifs&&<Modal title="Notifications" close={()=>setNotifs(false)}>{notifications.map(n=><div className="topic-row" key={n}><Bell size={18}/><span>{n}</span></div>)}</Modal>}
  {page==="home"&&<HomePage stats={stats} subject={subject} setSubject={setSubject} courseLevel={courseLevel} setCourseLevel={setCourseLevel} setPage={setPage}/>}
  {page==="study"&&<Study user={user} subject={subject} setSubject={setSubject} courseLevel={courseLevel} setCourseLevel={setCourseLevel} reload={load} notify={notify} profile={profile}/>}
  {page==="quests"&&<Quests stats={stats} setPage={setPage}/>} {page==="leaderboard"&&<SchoolLeaderboard profile={profile}/>} {page==="house"&&<HouseCup school={profile?.school}/>} {page==="friends"&&<Friends user={user} friends={friends} reload={load} notify={notify}/>} {page==="shop"&&<Shop profile={profile} reload={load} notify={notify}/>} {page==="character"&&<Character profile={profile} setProfile={setProfile} notify={notify}/>} {page==="ai"&&<AI stats={stats} sessions={sessions} profile={profile} subject={subject} courseLevel={courseLevel}/>} {page==="stats"&&<Stats stats={stats} sessions={sessions}/>} {page==="settings"&&<SettingsPage profile={profile} setProfile={setProfile} notify={notify} theme={theme} setTheme={setTheme}/>}</main></div>
}
function pageTitle(p){return({home:"Home Kingdom",quests:"Daily Quests",study:"Study Session",leaderboard:"School Leaderboard",house:"House Cup",friends:"Friends",shop:"Boost Shop",character:"Customise Character",ai:"AI Study Coach",stats:"Stats",settings:"Settings"}[p]||titleCase(p))}
function Fox({tiny}){return <div className={tiny?"fox tiny":"fox"}><span className="crown">👑</span><span className="face">🦊</span></div>}
function Nav({page,setPage,id,icon,label}){return <button className={`nav ${page===id?"active":""}`} onClick={()=>setPage(id)}>{React.cloneElement(icon,{size:20})}<span>{label}</span></button>}
function ProfileCard({profile,stats}){return <div className="player"><div className="avatar-big">{profile?.avatar||"🦊"}</div><b>@{profile?.username||"Student"}</b><span>{profile?.school||"School"}</span><small>{profile?.house||"NITH"} · Level {stats.levelNum}</small><div className="bar"><i style={{width:`${Math.min(100,(stats.xp%800)/8)}%`}}/></div><small>{stats.xp%800}/800 XP</small><div className="wallet"><span>🪙 {stats.coins}</span><span>💎 {stats.gems}</span></div></div>}
function PageHeader({title,profile,stats,theme,setTheme,setNotifs}){return <header className="page-head"><div><h1>{title}</h1><p>{profile?.school||"Your School"} · {profile?.house||"NITH"} House</p></div><div className="header-actions"><span className="chip">🔥 {stats.streak}</span><span className="chip">🪙 {stats.coins}</span><span className="chip">💎 {stats.gems}</span><button className="circle" onClick={()=>setNotifs(true)}><Bell size={18}/></button><button className="circle" onClick={()=>setTheme(theme==="light"?"dark":"light")}>{theme==="light"?<Moon size={18}/>:<Sun size={18}/>}</button><span className="mini-avatar">{profile?.avatar||"🦊"}</span></div></header>}
function HomePage({stats,subject,setSubject,courseLevel,setCourseLevel,setPage}){return <div className="home-grid"><section className="hero"><div><h1>Keep Your Streak Alive!</h1><p>{courseLevel} {subject}: Study Today And Earn XP, Coins And Gems.</p><button onClick={()=>setPage("study")}>Start Study Session</button></div><Fox/></section><section className="quest-card"><h2>🎯 Daily Quest</h2><p>Complete 3 Study Sessions</p><Progress value={Math.min(100,stats.todayCount/3*100)}/><b>{stats.todayCount} / 3</b><div className="rewards"><span>💜 100 XP</span><span>🪙 50</span><span>🎁</span></div>{stats.activeBoost&&<p className="boost-active">Active Boost: {boostName(stats.activeBoost)}</p>}</section><section className="card selectors"><div><h2>Choose Subject</h2><SubjectPicker subject={subject} setSubject={setSubject}/></div><div><h2>Choose Level</h2><LevelPicker courseLevel={courseLevel} setCourseLevel={setCourseLevel}/></div></section><TopicMap subject={subject} courseLevel={courseLevel}/><Activity stats={stats}/></div>}
function SubjectPicker({subject,setSubject}){return <div className="subject-grid">{Object.entries(TOPICS).map(([name,s])=><button key={name} className={`subject ${s.color} ${subject===name?"selected":""}`} onClick={()=>setSubject(name)}>{React.cloneElement(s.icon,{size:22})}<b>{name}</b></button>)}</div>}
function LevelPicker({courseLevel,setCourseLevel}){return <div className="level-grid">{LEVELS.map(l=><button key={l} className={courseLevel===l?"level selected":"level"} onClick={()=>setCourseLevel(l)}>{l}</button>)}</div>}
function Progress({value}){return <div className="progress"><i style={{width:`${Math.max(0,Math.min(100,value))}%`}}/></div>}
function TopicMap({subject,courseLevel}){const[open,setOpen]=useState(false),[selected,setSelected]=useState(null),course=TOPICS[subject],topics=course[courseLevel];return <section className="card map-card"><div className="head"><h2>{courseLevel} {subject} Quest Map</h2><button onClick={()=>setOpen(true)}>View Topics ›</button></div><div className="map-v2">{topics.map(([title,summary],i)=><button className={`topic-node ${course.color} ${i>1?"locked":""}`} key={title} onClick={()=>setSelected({title,summary,i})}><span>{i>1?<Lock/>:<Star/>}</span><b>{title}</b><small>{i>1?"Locked":"Open"}</small></button>)}</div>{open&&<Modal title={`${courseLevel} ${subject} Topics`} close={()=>setOpen(false)}>{topics.map(([t,s],i)=><div className="topic-row clickable" key={t} onClick={()=>setSelected({title:t,summary:s,i})}><b>{i+1}</b><div><strong>{t}</strong><p>{s}</p></div></div>)}</Modal>}{selected&&<Modal title={selected.title} close={()=>setSelected(null)}><p className="summary">{selected.summary}</p><div className="study-tips"><h3>What To Revise</h3><ul><li>Learn The Key Definitions.</li><li>Practise Exam-Style Questions.</li><li>Write A Short Summary In Your Own Words.</li></ul></div></Modal>}</section>}
function Modal({title,close,children}){return <div className="modal-back" onClick={close}><div className="modal" onClick={e=>e.stopPropagation()}><button className="modal-x" onClick={close}><X/></button><h2>{title}</h2>{children}</div></div>}
function Activity({stats}){return <section className="card activity"><div className="head"><h2>📅 Today's Activity</h2></div><div className="activity-grid"><Mini icon="🕒" label="Study Time" value={minutesLabel(stats.todayMinutes)} goal="Goal: 3h 00m" pct={Math.min(100,stats.todayMinutes/180*100)}/><Mini icon="🎯" label="Sessions" value={`${stats.todayCount} / 4`} goal="Daily Goal" pct={Math.min(100,stats.todayCount/4*100)}/><Mini icon="⚡" label="XP Earned" value={stats.xp} goal="Level Progress" pct={Math.min(100,(stats.xp%800)/8)}/></div></section>}
function Mini({icon,label,value,goal,pct}){return <div className="mini"><span>{icon}</span><div><small>{label}</small><b>{value}</b><em>{goal}</em><Progress value={pct}/></div></div>}
function Study({user,subject,setSubject,courseLevel,setCourseLevel,reload,notify,profile}){const[running,setRunning]=useState(false),[seconds,setSeconds]=useState(0),[notes,setNotes]=useState("");useEffect(()=>{if(!running)return;const t=setInterval(()=>setSeconds(s=>s+1),1000);return()=>clearInterval(t)},[running]);const minutes=Math.max(1,Math.floor(seconds/60));async function save(){let xp=minutes+(minutes>=60?50:0),coins=Math.max(1,Math.floor(xp/10)),gems=minutes>=45?1:0;if(profile?.active_boost==="double_xp")xp*=2;if(profile?.active_boost==="coin_charm")coins*=2;if(profile?.active_boost==="gem_finder")gems+=2;const{error}=await supabase.from("study_sessions").insert({user_id:user.id,subject,minutes,xp,notes,check_in:`${courseLevel}: ${notes}`,session_date:today()});if(error){notify(error.message);return}await supabase.from("profiles").update({coins:Number(profile?.coins||0)+coins,gems:Number(profile?.gems||0)+gems,active_boost:null}).eq("id",user.id);notify(`Quest Complete: ${minutes} Min · ${xp} XP · ${coins} Coins · ${gems} Gems`);setRunning(false);setSeconds(0);setNotes("");reload()}return <section className="page study"><h1>Study Session</h1><SubjectPicker subject={subject} setSubject={setSubject}/><LevelPicker courseLevel={courseLevel} setCourseLevel={setCourseLevel}/><div className="timer"><span className="timer-animal">{profile?.avatar||"🦊"}</span><b>{String(Math.floor(seconds/3600)).padStart(2,"0")}:{String(Math.floor(seconds/60)%60).padStart(2,"0")}:{String(seconds%60).padStart(2,"0")}</b><span>{courseLevel} {subject} Quest In Progress</span></div><textarea value={notes} onChange={e=>setNotes(e.target.value)} placeholder="Write What You Revised Or One Thing You Learned..."/><div className="actions">{!running?<button onClick={()=>setRunning(true)}><Play/>Start</button>:<button onClick={()=>setRunning(false)}>Pause</button>}<button className="green" onClick={save}><CheckCircle2/>End & Save</button></div></section>}
function Quests({stats,setPage}){return <section className="page"><h1>Daily Quests</h1><Quest title="Complete 3 Study Sessions" progress={stats.todayCount} goal={3}/><Quest title="Study For 45 Minutes" progress={stats.todayMinutes} goal={45}/><Quest title="Keep Your Streak Alive" progress={stats.streak>0?1:0} goal={1}/><button onClick={()=>setPage("study")}>Start A Quest</button></section>}
function Quest({title,progress,goal}){return <div className="quest"><Target/><div><b>{title}</b><Progress value={Math.min(100,progress/goal*100)}/><small>{progress}/{goal} · Reward Available</small></div></div>}
function SchoolLeaderboard({profile}){const[rows,setRows]=useState([]);useEffect(()=>{if(!profile?.school)return;supabase.from("leaderboard_weekly").select("*").eq("school",profile.school).limit(50).then(({data})=>setRows(data||[]))},[profile?.school]);return <section className="page"><h1>{profile?.school||"School"} Leaderboard</h1>{rows.map((r,i)=><div className="leader" key={r.user_id}><span>#{i+1}</span><b>@{r.username}</b><em>{minutesLabel(r.minutes)}</em><strong>{r.xp} XP</strong></div>)}{!rows.length&&<p>No Leaderboard Data Yet. Save A Study Session To Appear Here.</p>}</section>}
function HouseCup({school}){const[rows,setRows]=useState([]);useEffect(()=>{supabase.from("house_leaderboard").select("*").eq("school",school||"").then(({data})=>setRows(data||[]))},[school]);const all=HOUSES.map((h,i)=>rows.find(r=>r.house===h)||{house:h,xp:0,color:["red","blue","green"][i]});return <section className="page house"><h1>🏆 House Cup</h1><p>House Points Start At 0 And Rise When Students Earn XP.</p>{all.map((h,i)=><div className={`house-row ${["red","blue","green"][i]}`} key={h.house}><Shield/><b>{h.house}</b><span>{h.xp||0} Pts</span></div>)}</section>}
function Friends({user,friends,reload,notify}){const[query,setQuery]=useState(""),[results,setResults]=useState([]);async function search(){const q=query.trim();if(!q)return;const{data}=await supabase.from("profiles").select("id,username,display_name,school").ilike("username",`%${q}%`).limit(8);setResults((data||[]).filter(p=>p.id!==user.id))}async function add(p){const{error}=await supabase.from("friends").insert({requester:user.id,receiver:p.id,status:"accepted"});if(error){notify(error.message);return}notify(`Added @${p.username}`);setResults([]);setQuery("");reload()}return <section className="page"><h1>Friends</h1><p>Search By Username. School Is Shown So You Know Who You Are Adding.</p><div className="inline"><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search Username, e.g. Baker07"/><button onClick={search}><Search/>Search</button></div>{results.map(p=><div className="friend" key={p.id}><b>@{p.username}</b><span>{p.school}</span><button onClick={()=>add(p)}>Add</button></div>)}<h2>Your Friends</h2>{friends.map(f=><div className="friend" key={f.id}>👥 {f.friend_username?`@${f.friend_username}`:f.friend_email||"Friend"}</div>)}</section>}
function boostName(id){return SHOP.find(x=>x.id===id)?.name||id}
function Shop({profile,reload,notify}){async function buy(item){if(profile?.active_boost){notify("Use Your Current Boost Before Buying Another.");return}const coins=Number(profile?.coins||0),gems=Number(profile?.gems||0);if(item.costType==="coins"&&coins<item.cost){notify("You Don't Have Enough Coins.");return}if(item.costType==="gems"&&gems<item.cost){notify("You Don't Have Enough Gems.");return}const patch={active_boost:item.id};if(item.costType==="coins")patch.coins=coins-item.cost;else patch.gems=gems-item.cost;const{error}=await supabase.from("profiles").update(patch).eq("id",profile.id);if(error){notify(error.message);return}notify(`${item.name} Activated For Your Next Session.`);reload()}return <section className="page"><h1>Boost Shop</h1><p>Your Balance: 🪙 {profile?.coins||0} Coins · 💎 {profile?.gems||0} Gems</p>{profile?.active_boost&&<div className="notice good">Active Boost: {boostName(profile.active_boost)}</div>}<div className="shop-grid">{SHOP.map(item=><div className="shop" key={item.id}><span>{item.icon}</span><b>{item.name}</b><p>{item.desc}</p><strong>{item.cost} {titleCase(item.costType)}</strong><button onClick={()=>buy(item)}>Buy And Activate</button></div>)}</div></section>}
function Character({profile,setProfile,notify}){const[avatar,setAvatar]=useState(profile?.avatar||"🦊");async function save(){const{data,error}=await supabase.from("profiles").update({avatar}).eq("id",profile.id).select("*").single();if(error){notify(error.message);return}setProfile(data);notify("Character Saved.")}return <section className="page character"><h1>Customise Character</h1><div className="character-preview">{avatar}</div><AvatarPicker avatar={avatar} setAvatar={setAvatar}/><button onClick={save}><Palette/>Save Character</button></section>}
function AvatarPicker({avatar,setAvatar}){return <div className="avatar-grid">{AVATARS.map(a=><button key={a} className={avatar===a?"avatar-choice selected":"avatar-choice"} onClick={()=>setAvatar(a)}>{a}</button>)}</div>}
function AI({stats,sessions,profile,subject,courseLevel}){const[q,setQ]=useState(""),[answer,setAnswer]=useState(""),[busy,setBusy]=useState(false);async function ask(prompt){const question=prompt||q||`Make Me A ${courseLevel} ${subject} Revision Plan.`;setBusy(true);try{const res=await fetch("/api/ai-study-coach",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({question,stats,recentSessions:sessions.slice(0,20),profile,subject,level:courseLevel})});const data=await res.json();setAnswer(data.answer||"Try Again.")}catch{setAnswer("AI Could Not Respond Right Now.")}setBusy(false)}return <section className="page ai"><h1>AI Study Coach 🤖</h1><div className="quick"><button onClick={()=>ask(`Make Me A ${courseLevel} ${subject} Revision Plan`)}>Revision Plan</button><button onClick={()=>ask("Which Subject Am I Neglecting?")}>Weak Spots</button><button onClick={()=>ask("How Do I Keep My Streak?")}>Streak Advice</button></div><div className="ai-chat"><input value={q} onChange={e=>setQ(e.target.value)} placeholder="Ask Anything About Studying..." onKeyDown={e=>{if(e.key==="Enter")ask()}}/><button onClick={()=>ask()}><Send/>Ask</button></div><pre>{busy?"Thinking...":answer||"Ask Your AI Coach For Revision Tips."}</pre>{answer&&<button onClick={()=>copyText(answer)}><Copy/>Copy</button>}</section>}
function Stats({stats,sessions}){return <section className="page"><h1>Stats</h1><div className="stats-grid"><Metric icon="🔥" value={stats.streak} label="Streak"/><Metric icon="⚡" value={stats.xp} label="XP"/><Metric icon="🕒" value={minutesLabel(stats.total)} label="Total Study"/></div>{Object.keys(TOPICS).map(s=>{const m=sessions.filter(x=>x.subject===s).reduce((a,x)=>a+Number(x.minutes||0),0);return <div className="subject-stat" key={s}><b>{s}</b><Progress value={Math.min(100,m/300*100)}/><span>{minutesLabel(m)}</span></div>})}</section>}
function SettingsPage({profile,setProfile,notify,theme,setTheme}){const[name,setName]=useState(profile?.display_name||""),[username,setUsername]=useState(profile?.username||""),[school,setSchool]=useState(profile?.school||SCHOOLS[0]),[house,setHouse]=useState(profile?.house||"NITH");async function save(){const{data,error}=await supabase.from("profiles").update({display_name:name,username,school,house}).eq("id",profile.id).select("*").single();if(error){notify(error.message);return}setProfile(data);notify("Settings Saved.")}return <section className="page"><h1>Settings</h1><label>Display Name</label><input value={name} onChange={e=>setName(e.target.value)}/><label>Username</label><input value={username} onChange={e=>setUsername(e.target.value)}/><label>School</label><select value={school} onChange={e=>setSchool(e.target.value)}>{SCHOOLS.map(s=><option key={s}>{s}</option>)}</select><label>House</label><select value={house} onChange={e=>setHouse(e.target.value)}>{HOUSES.map(h=><option key={h}>{h}</option>)}</select><button onClick={save}>Save</button><button className="plain" onClick={()=>setTheme(theme==="light"?"dark":"light")}>Switch Theme</button></section>}

createRoot(document.getElementById("root")).render(<App/>);
