import React,{useEffect,useMemo,useState} from "react";
import {createRoot} from "react-dom/client";
import {createClient} from "@supabase/supabase-js";
import {Home,Timer,Play,Square,Trophy,Flame,Users,Brain,Medal,Settings,LogOut,PlusCircle,UserPlus,Send,Copy,CalendarDays,Crown,Zap,Sun,Moon} from "lucide-react";
import {ResponsiveContainer,BarChart,Bar,XAxis,YAxis,Tooltip} from "recharts";
import "./styles.css";

const supabase=createClient(import.meta.env.VITE_SUPABASE_URL||"",import.meta.env.VITE_SUPABASE_ANON_KEY||"");
const SUBJECTS=["Biology","Chemistry","Physics","Maths","English","History","Geography","Computing","Business","Other"];
function today(){return new Date().toISOString().slice(0,10)}
function minutesLabel(min){const h=Math.floor(Number(min||0)/60),m=Number(min||0)%60;return h?`${h}h ${m}m`:`${m}m`}
function xpToLevel(xp){return Math.max(1,Math.floor(Math.sqrt(Number(xp||0)/75))+1)}
function copyText(text){navigator.clipboard?.writeText(String(text||""))}
function weekStartKey(date=new Date()){const d=new Date(date);const day=(d.getDay()+6)%7;d.setDate(d.getDate()-day);return d.toISOString().slice(0,10)}
function calcStreak(sessions){const days=[...new Set((sessions||[]).map(s=>s.session_date))].sort().reverse();let streak=0,d=new Date(today()+"T00:00:00");for(let i=0;i<365;i++){const k=d.toISOString().slice(0,10);if(days.includes(k)){streak++;d.setDate(d.getDate()-1);continue}if(i===0){d.setDate(d.getDate()-1);continue}break}return streak}
function longestStreak(sessions){const days=[...new Set((sessions||[]).map(s=>s.session_date))].sort();let best=0,cur=0,last=null;for(const day of days){const d=new Date(day+"T00:00:00");cur=last&&(d-last)/(86400000)===1?cur+1:1;best=Math.max(best,cur);last=d}return best}

function App(){
  const [session,setSession]=useState(null),[loading,setLoading]=useState(true),[theme,setTheme]=useState(localStorage.getItem("ss_theme")||"dark");
  useEffect(()=>{document.body.dataset.theme=theme;localStorage.setItem("ss_theme",theme)},[theme]);
  useEffect(()=>{supabase.auth.getSession().then(({data})=>{setSession(data.session);setLoading(false)});const {data:{subscription}}=supabase.auth.onAuthStateChange((_e,s)=>setSession(s));return()=>subscription.unsubscribe()},[]);
  if(loading)return <div className="loading">Loading StudyStreak...</div>;
  if(!session)return <Auth theme={theme} setTheme={setTheme}/>;
  return <Dashboard user={session.user} theme={theme} setTheme={setTheme}/>;
}

function Auth({theme,setTheme}){
  const [mode,setMode]=useState("login"),[email,setEmail]=useState(""),[password,setPassword]=useState(""),[msg,setMsg]=useState(""),[err,setErr]=useState("");
  async function signUp(){setErr("");setMsg("");if(password.length<6){setErr("Password needs at least 6 characters.");return}const {error}=await supabase.auth.signUp({email,password});error?setErr(error.message):setMsg("Account created. Check your email if confirmation is required.")}
  async function signIn(){setErr("");setMsg("");const {error}=await supabase.auth.signInWithPassword({email,password});if(error)setErr(error.message)}
  return <main className="auth"><section className="auth-card"><div className="brand"><span><Flame/></span><b>StudyStreak</b></div><h1>{mode==="login"?"Welcome back":"Create your study account"}</h1><p>Turn revision into streaks, XP, leaderboards, achievements, and friendly competitions.</p><div className="tabs"><button className={mode==="login"?"active":""} onClick={()=>setMode("login")}>Sign In</button><button className={mode==="signup"?"active":""} onClick={()=>setMode("signup")}>Create Account</button></div>{err&&<p className="error">{err}</p>}{msg&&<p className="successBox">{msg}</p>}<label>Email</label><input value={email} onChange={e=>setEmail(e.target.value)} placeholder="you@example.com"/><label>Password</label><input type="password" value={password} onChange={e=>setPassword(e.target.value)} placeholder="Your password"/><button className="primary wide" onClick={mode==="login"?signIn:signUp}>{mode==="login"?"Sign In":"Create Account"}</button><button className="ghost wide" onClick={()=>setTheme(theme==="dark"?"light":"dark")}>{theme==="dark"?<Sun/>:<Moon/>} Switch Theme</button></section><section className="auth-hero"><div className="hero-card"><h2>Study like it’s a game.</h2><p>Compete with friends, protect your streak, earn achievements, and let AI guide your revision.</p></div></section></main>
}

function Dashboard({user,theme,setTheme}){
  const [page,setPage]=useState("home"),[profile,setProfile]=useState(null),[sessions,setSessions]=useState([]),[friends,setFriends]=useState([]),[competitions,setCompetitions]=useState([]),[toast,setToast]=useState(""),[loading,setLoading]=useState(true);
  function notify(t){setToast(t);setTimeout(()=>setToast(""),2600)}
  async function load(){setLoading(true);let {data:p}=await supabase.from("profiles").select("*").eq("id",user.id).maybeSingle();if(!p){const username=(user.email||"student").split("@")[0];const {data:newP}=await supabase.from("profiles").insert({id:user.id,email:user.email,username,display_name:username}).select("*").single();p=newP}const [s,f,c]=await Promise.all([supabase.from("study_sessions").select("*").eq("user_id",user.id).order("created_at",{ascending:false}),supabase.from("friends_view").select("*").or(`requester.eq.${user.id},receiver.eq.${user.id}`),supabase.from("competition_members").select("*,competitions(*)").eq("user_id",user.id)]);setProfile(p);setSessions(s.data||[]);setFriends(f.data||[]);setCompetitions(c.data||[]);setLoading(false)}
  useEffect(()=>{load()},[]);
  const stats=useMemo(()=>{const totalMinutes=sessions.reduce((a,s)=>a+Number(s.minutes||0),0),xp=sessions.reduce((a,s)=>a+Number(s.xp||0),0),week=sessions.filter(s=>s.session_date>=weekStartKey());return{totalMinutes,xp,level:xpToLevel(xp),streak:calcStreak(sessions),longest:longestStreak(sessions),weekMinutes:week.reduce((a,s)=>a+Number(s.minutes||0),0),sessions:sessions.length}},[sessions]);
  const chart=useMemo(()=>{const map={};for(let i=6;i>=0;i--){const d=new Date();d.setDate(d.getDate()-i);map[d.toISOString().slice(0,10)]=0}sessions.forEach(s=>{if(map[s.session_date]!=null)map[s.session_date]+=Number(s.minutes||0)});return Object.entries(map).map(([date,minutes])=>({date:date.slice(5),minutes}))},[sessions]);
  if(loading)return <div className="loading">Loading your streak...</div>;
  return <div className="app-shell"><aside className="sidebar"><div className="brand small"><span><Flame/></span><b>StudyStreak</b></div><Nav page={page} setPage={setPage} id="home" icon={<Home/>} label="Dashboard"/><Nav page={page} setPage={setPage} id="timer" icon={<Timer/>} label="Timer"/><Nav page={page} setPage={setPage} id="leaderboard" icon={<Trophy/>} label="Leaderboard"/><Nav page={page} setPage={setPage} id="friends" icon={<Users/>} label="Friends"/><Nav page={page} setPage={setPage} id="achievements" icon={<Medal/>} label="Achievements"/><Nav page={page} setPage={setPage} id="competitions" icon={<Crown/>} label="Competitions"/><Nav page={page} setPage={setPage} id="ai" icon={<Brain/>} label="AI Coach"/><Nav page={page} setPage={setPage} id="settings" icon={<Settings/>} label="Settings"/><button className="logout" onClick={()=>supabase.auth.signOut()}><LogOut/> Sign Out</button></aside><main className="content"><div className="topbar"><div><b>{profile?.display_name||profile?.username}</b><span>Level {stats.level}</span></div><button className="circle" onClick={()=>setTheme(theme==="dark"?"light":"dark")}>{theme==="dark"?<Sun/>:<Moon/>}</button></div>{toast&&<div className="toast">{toast}</div>}{page==="home"&&<HomePage stats={stats} chart={chart} sessions={sessions}/>} {page==="timer"&&<StudyTimer user={user} reload={load} notify={notify}/>} {page==="leaderboard"&&<Leaderboard/>}{page==="friends"&&<Friends user={user} friends={friends} reload={load} notify={notify}/>} {page==="achievements"&&<Achievements stats={stats} sessions={sessions}/>} {page==="competitions"&&<Competitions user={user} competitions={competitions} reload={load} notify={notify}/>} {page==="ai"&&<AICoach stats={stats} sessions={sessions} profile={profile}/>} {page==="settings"&&<SettingsPage profile={profile} setProfile={setProfile} notify={notify}/>}</main></div>
}
function Nav({page,setPage,id,icon,label}){return <button className={`nav ${page===id?"active":""}`} onClick={()=>setPage(id)}>{React.cloneElement(icon,{size:18})}<span>{label}</span></button>}
function Stat({icon,label,value,trend}){return <section className="stat">{icon&&React.cloneElement(icon,{size:20})}<span>{label}</span><b>{value}</b><small>{trend}</small></section>}
function Header({title,note}){return <header className="page-head"><h1>{title}</h1><p>{note}</p></header>}

function HomePage({stats,chart,sessions}){const subjects=[...new Set(sessions.map(s=>s.subject))].filter(Boolean);return <><section className="hero"><div><p className="eyebrow">Study Command Centre</p><h1>Keep your streak alive 🔥</h1><p>Study daily, earn XP, climb leaderboards, and become consistent without burning out.</p></div><div className="streak-orb"><Flame/><span>Current Streak</span><b>{stats.streak}</b><small>days</small></div></section><div className="grid kpis"><Stat icon={<Flame/>} label="Current Streak" value={`${stats.streak} days`} trend={`Best: ${stats.longest}`}/><Stat icon={<Timer/>} label="Total Study" value={minutesLabel(stats.totalMinutes)} trend={`${stats.sessions} sessions`}/><Stat icon={<Zap/>} label="XP" value={stats.xp} trend={`Level ${stats.level}`}/><Stat icon={<CalendarDays/>} label="This Week" value={minutesLabel(stats.weekMinutes)} trend="Monday to Sunday"/></div><div className="split"><section className="card"><h2>7-Day Progress</h2><ResponsiveContainer width="100%" height={280}><BarChart data={chart}><XAxis dataKey="date"/><YAxis/><Tooltip/><Bar dataKey="minutes"/></BarChart></ResponsiveContainer></section><section className="card"><h2>Subjects Studied</h2>{subjects.length?subjects.map(s=><span className="subject-pill" key={s}>{s}</span>):<p className="muted">Start a session to build your subject history.</p>}</section></div></>}
function StudyTimer({user,reload,notify}){const [running,setRunning]=useState(false),[seconds,setSeconds]=useState(0),[subject,setSubject]=useState("Biology"),[notes,setNotes]=useState(""),[checkIn,setCheckIn]=useState("");useEffect(()=>{if(!running)return;const t=setInterval(()=>setSeconds(s=>s+1),1000);return()=>clearInterval(t)},[running]);const minutes=Math.max(1,Math.floor(seconds/60));async function save(){const xp=minutes+(minutes>=60?25:0);const {error}=await supabase.from("study_sessions").insert({user_id:user.id,subject,minutes,xp,notes,check_in:checkIn,session_date:today()});if(error){notify(error.message);return}notify(`Session saved: ${minutes} min · ${xp} XP`);setRunning(false);setSeconds(0);setNotes("");setCheckIn("");reload()}return <><Header title="Study Timer" note="Start a focused session. Add notes to keep sessions honest and useful."/><section className="timer-card"><div className="timer-display">{String(Math.floor(seconds/3600)).padStart(2,"0")}:{String(Math.floor(seconds/60)%60).padStart(2,"0")}:{String(seconds%60).padStart(2,"0")}</div><div className="form"><select value={subject} onChange={e=>setSubject(e.target.value)}>{SUBJECTS.map(s=><option key={s}>{s}</option>)}</select><textarea placeholder="What did you study?" value={notes} onChange={e=>setNotes(e.target.value)}/><input placeholder="Random check-in: write one thing you learned" value={checkIn} onChange={e=>setCheckIn(e.target.value)}/></div><div className="actions">{!running?<button className="primary" onClick={()=>setRunning(true)}><Play/>Start</button>:<button onClick={()=>setRunning(false)}><Square/>Pause</button>}<button className="success" onClick={save}>End & Save</button></div></section></>}
function Leaderboard(){const [rows,setRows]=useState([]);useEffect(()=>{supabase.from("leaderboard_weekly").select("*").limit(50).then(({data})=>setRows(data||[]))},[]);return <><Header title="Weekly Leaderboard" note="Rankings reset every week. Stay consistent."/><section className="card table-card"><table><thead><tr><th>Rank</th><th>Student</th><th>Hours</th><th>XP</th></tr></thead><tbody>{rows.map((r,i)=><tr key={r.user_id}><td>#{i+1}</td><td>{r.display_name||r.username}</td><td>{minutesLabel(r.minutes)}</td><td>{r.xp}</td></tr>)}</tbody></table>{!rows.length&&<p className="muted">No leaderboard data yet.</p>}</section></>}
function Friends({user,friends,reload,notify}){const [email,setEmail]=useState("");async function add(){const {data:p}=await supabase.from("profiles").select("*").eq("email",email.trim()).maybeSingle();if(!p){notify("No user found.");return}const {error}=await supabase.from("friends").insert({requester:user.id,receiver:p.id,status:"accepted"});if(error){notify(error.message);return}notify("Friend added.");setEmail("");reload()}return <><Header title="Friends" note="Compare streaks and progress with classmates."/><section className="card form"><input placeholder="Friend email" value={email} onChange={e=>setEmail(e.target.value)}/><button onClick={add}><UserPlus/>Add Friend</button></section><section className="card">{friends.length?friends.map(f=><div className="friend-row" key={f.id}><Users/><span>{f.friend_email||"Friend"}</span></div>):<p className="muted">No friends yet.</p>}</section></>}
function Achievements({stats,sessions}){const subjectCounts={};sessions.forEach(s=>subjectCounts[s.subject]=(subjectCounts[s.subject]||0)+Number(s.minutes||0));const achievements=[["🥉 First Session",stats.sessions>=1],["🥈 7-Day Streak",stats.streak>=7],["🥇 30-Day Streak",stats.streak>=30],["🔥 100 Hours Studied",stats.totalMinutes>=6000],["🧠 Biology Champion",(subjectCounts.Biology||0)>=600],["📚 Exam Warrior",Object.keys(subjectCounts).length>=5]];return <><Header title="Achievements" note="Earn badges for consistency and subject mastery."/><section className="achievement-grid">{achievements.map(([name,done])=><div className={`achievement ${done?"done":""}`} key={name}><Medal/><b>{name}</b><span>{done?"Unlocked":"Locked"}</span></div>)}</section></>}
function Competitions({user,competitions,reload,notify}){const [code,setCode]=useState("");async function createCompetition(){const join_code=Math.random().toString(36).slice(2,8).toUpperCase();const {data,error}=await supabase.from("competitions").insert({name:"New Study Battle",join_code,type:"friends"}).select("*").single();if(error){notify(error.message);return}await supabase.from("competition_members").insert({competition_id:data.id,user_id:user.id});notify(`Created. Code: ${join_code}`);reload()}async function join(){const {data:c}=await supabase.from("competitions").select("*").eq("join_code",code.trim().toUpperCase()).maybeSingle();if(!c){notify("Competition not found.");return}const {error}=await supabase.from("competition_members").insert({competition_id:c.id,user_id:user.id});if(error){notify(error.message);return}notify("Joined competition.");setCode("");reload()}return <><Header title="Competitions" note="Create friend battles, class battles, or house competitions."/><section className="card form"><button onClick={createCompetition}><PlusCircle/>Create Competition</button><input placeholder="Join code" value={code} onChange={e=>setCode(e.target.value)}/><button onClick={join}>Join</button></section><section className="card">{competitions.length?competitions.map(c=><div className="competition-row" key={c.id}><Crown/><div><b>{c.competitions?.name}</b><span>Code: {c.competitions?.join_code}</span></div></div>):<p className="muted">No competitions yet.</p>}</section></>}
function AICoach({stats,sessions,profile}){const [q,setQ]=useState(""),[answer,setAnswer]=useState(""),[busy,setBusy]=useState(false);async function ask(prompt){const question=prompt||q||"Give me a study plan for this week.";setBusy(true);setAnswer("");try{const res=await fetch("/api/ai-study-coach",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({question,stats,recentSessions:sessions.slice(0,20),profile})});const data=await res.json();setAnswer(data.answer||"Try asking again.")}catch{setAnswer("AI could not respond right now. Try again soon.")}setBusy(false)}return <><Header title="AI Study Coach" note="Get personalised revision advice based on your sessions and subjects."/><section className="card ai-card"><div className="quick-prompts"><button onClick={()=>ask("Make me a revision plan for this week")}>Weekly Plan</button><button onClick={()=>ask("Which subject am I neglecting?")}>Weak Spots</button><button onClick={()=>ask("How do I protect my streak?")}>Streak Advice</button></div><div className="ai-chat"><input value={q} onChange={e=>setQ(e.target.value)} placeholder="Ask anything about studying..." onKeyDown={e=>{if(e.key==="Enter")ask()}}/><button onClick={()=>ask()}><Send/>{busy?"Thinking...":"Ask AI"}</button></div><pre className="ai-answer">{busy?"AI is thinking...":answer||"Ask me for a revision plan, subject advice, or motivation."}</pre>{answer&&<button className="secondary" onClick={()=>copyText(answer)}><Copy/>Copy</button>}</section></>}
function SettingsPage({profile,setProfile,notify}){const [name,setName]=useState(profile?.display_name||""),[house,setHouse]=useState(profile?.house||""),[year,setYear]=useState(profile?.year_group||"");async function save(){const {data,error}=await supabase.from("profiles").update({display_name:name,house,year_group:year}).eq("id",profile.id).select("*").single();if(error){notify(error.message);return}setProfile(data);notify("Settings saved.")}return <><Header title="Settings" note="Customise your study profile."/><section className="card form"><input placeholder="Display name" value={name} onChange={e=>setName(e.target.value)}/><input placeholder="House e.g. Blue House" value={house} onChange={e=>setHouse(e.target.value)}/><input placeholder="Year group e.g. S5" value={year} onChange={e=>setYear(e.target.value)}/><button onClick={save}>Save</button></section></>}

createRoot(document.getElementById("root")).render(<App/>);
